# These are supported funding model platforms

github: Ragdata
patreon: ragdata
# open_collective:
ko_fi: ragdata
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie: Ragdata
custom: paypal.me/Ragdata
